name: Trigger auto deployment for frameworksangular9b808b9d

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/frameworksangular9b808b9d-AutoDeployTrigger-30b7d9a3-1a8f-4cf1-806d-1f50d7c36fc3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FRAMEWORKSANGULAR9B808B9D_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRAMEWORKSANGULAR9B808B9D_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRAMEWORKSANGULAR9B808B9D_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.FRAMEWORKSANGULAR9B808B9D_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRAMEWORKSANGULAR9B808B9D_REGISTRY_PASSWORD }}
          containerAppName: frameworksangular9b808b9d
          resourceGroup: frameworksangular9b80
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


